---
title: "`r emo::ji('light_rail')` Commuters in Germany"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: bootstrap
    css: "css/fonts.css"
    source_code: embed
runtime: shiny_prerendered
---

<!-- Import stylesheets -->
<link href="https://code.cdn.mozilla.net/fonts/fira.css" rel="stylesheet"> 
<link href="https://code.cdn.mozilla.net/fonts/zilla-slab.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5/distr/fira_code.css" rel="stylesheet">

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(reactable)
library(htmltools)
library(highcharter)
library(colorspace)
```

```{r data, include=FALSE}
laender_df <- readr::read_csv("laender_df.csv")
nuts1_geojson <- download_map_data("countries/de/de-all")
```

Sidebar {.sidebar}
=======================================================================

Access to official data provided by the [datenguide API](https://github.com/datenguide/datenguide-api) -- using the [datenguidepy](https://github.com/CorrelAid/datenguide-python) package

---

```{r ui-input}
sliderInput("year", label = "Year:",
            min = 2011, max = 2019, value = 2019, step = 1, ticks = FALSE, sep = "")

selectInput("plot_var", label = "Statistic to plot:",
            choices = c("In", "Out", "Balance"), selected = "Balance")

radioButtons("choose_pct", label = "As a percentage of the population?",
             choices = c("Yes", "No"), selected = "No")
```

```{r prep-df, context="server"}
transform_stats <- function(data, to_pct = input$choose_pct) {
  if (to_pct == "Yes") {
    data %>% 
      mutate(across(c(In, Out, Balance), ~ round(.x * 100 / pop, 2)))
  } else {
    data
  }
}

laender_df_trans <- reactive({
  laender_df %>% 
    transform_stats()
})
```

Across Bundesländer (NUTS-1) {data-icon="fa-th-list"}
=======================================================================

Column {data-width=7, .tabset}
-----------------------------------------------------------------------

### `r emo::ji("clipboard")` Table

```{r laender-tbl-rndr}
reactableOutput("laender_tbl")
```

```{r barchart-tbl-fn, context="server"}
bar_chart <- function(label, width = "100%", height = "14px", fill = "#cccccc",
                      align = "left") {
  label <- div(style = list(marginLeft = "5px", marginRight = "5px"), label)
  bar <- div(style = list(background = fill, width = width, height = height,
                          float = align))
  if (align == "right") {
    div(style = list(display = "flex", alignItems = "center",
                     justifyContent = "flex-end"), label, bar)
  } else {
    div(style = list(display = "flex", alignItems = "center"), bar, label)
  }
}
```

```{r laender-tbl-srvr, context="server"}
output$laender_tbl <- renderReactable({
  laender_df_trans() %>% 
    filter(year == input$year) %>% 
    select(name, Out, Balance, In) %>% 
    reactable(
      defaultPageSize = 16, borderless = TRUE, wrap = FALSE,
      defaultSorted = "Balance", defaultSortOrder = "desc",
      columns = list(
        name = colDef(name = "Bundesland", defaultSortOrder = "asc"),
        Balance = colDef(
          name = emo::ji("balance_scale"),
          width = 80,
          cell = function(value) format(value, big.mark = " "),
          style = list(background = "#f8f8f8"),
          align = "center"
        ),
        Out = colDef(
          cell = function(value) {
            width <- paste0(value * .7 * 100 / max(.$Out), "%")
            value <- format(value, big.mark = " ")
            bar_chart(value, width = width, fill = "#c7522b", align = "right")
          }
        ),
        In = colDef(
          cell = function(value) {
            width <- paste0(value * .7 * 100 / max(.$Out), "%")
            value <- format(value, big.mark = " ")
            bar_chart(value, width = width, fill = "#008585", align = "left")
          },
          align = "left"
        )
      )
    )
})
```

### `r emo::ji("world_map")` Choropleth map

```{r laender-map-rndr}
highchartOutput("laender_map")
```

```{r mapcols-fn, context="server"}
hc_map_colors <- function(hc_map, var) {
  if (var == "Balance") {
      ret <- hc_map %>% 
        hc_colorAxis(min = NULL, stops = color_stops(
          colors = divergingx_hcl(12, rev = TRUE)[3:12]
        ))
  }
  if (var == "In") {
      ret <- hc_map %>% 
        hc_colorAxis(stops = color_stops(
          colors = divergingx_hcl(20, rev = TRUE)[11:20]
        ))
  }
  if (var == "Out") {
      ret <- hc_map %>% 
        hc_colorAxis(stops = color_stops(
          colors = divergingx_hcl(20)[11:20]
        ))
  }
  ret
}
```

```{r laender-map-srvr, context="server"}
output$laender_map <- renderHighchart({
  highchart() %>% 
    hc_add_series_map(
    map = nuts1_geojson,
    df = laender_df_trans() %>% 
      filter(year == input$year),
    value = input$plot_var,
    joinBy = "name",
    name = input$plot_var,
    dataLabels = list(enabled = TRUE, format = "{point.name}"),
    borderColor = "#fafafa",
    borderWidth = 0.1
  ) %>% 
    hc_map_colors(var = input$plot_var) %>% 
    hc_add_theme(hc_theme(chart = list(style = list(
      fontFamily = "var(--text-font-family), var(--text-font-base)",
      fontVariantNumeric = "tabular-nums"
    ))))
})
```

### `r emo::ji("chart_with_upwards_trend")` Time series

```{r laender-ts-rndr}
highchartOutput("laender_ts")
```

```{r laender-ts-srvr, context="server"}
output$laender_ts <- renderHighchart({
  laender_df_trans() %>% 
    hchart("line", hcaes(x = year, y = !!sym(input$plot_var), group = name),
           marker = list(enabled = FALSE)) %>% 
    hc_xAxis(title = "") %>% 
    hc_tooltip(crosshairs = TRUE, headerFormat = "") %>% 
    hc_add_theme(hc_theme(chart = list(style = list(
      fontFamily = "var(--text-font-family), var(--text-font-base)",
      fontVariantNumeric = "tabular-nums"
    ))))
})
```

Column {data-width=3}
-----------------------------------------------------------------------

### Total {.value-box}

```{r total-box-nuts1-rndr}
valueBoxOutput("total_box_in")
valueBoxOutput("total_box_out")
```

```{r calc-sum-fn, context="server"}
get_sum <- function(data, var) {
  if (input$choose_pct == "No") {
    value <- data %>% 
      filter(year == input$year) %>% 
      pull(.data[[var]]) %>% 
      sum() %>% 
      `/`(1e6) %>% 
      format(digits = 2, nsmall = 2) %>% 
      paste0(" M")
  } else {
    value <- data %>% 
      filter(year == input$year) %>% 
      summarise(sum = sum(.data[[var]]),
                pop = sum(pop)) %>% 
      mutate(pct = sum * 100 / pop) %>% 
      pull(pct) %>% 
      format(digits = 2, nsmall = 2)
  }
  paste0(var, ": ", value)
}
```

```{r total-box-nuts1-srvr, context="server"}
output$total_box_in <- renderValueBox({
  valueBox(
    laender_df %>% 
      get_sum("In"),
    color = "#f8f8f8"
  )
})

output$total_box_out <- renderValueBox({
  valueBox(
    laender_df %>% 
      get_sum("Out"),
    caption = paste0("Total in ", input$year), color = "#f8f8f8",
    if (input$choose_pct == "No") {
      icon = "fa-users"
    } else {
      icon = "fa-percent"
    }
  )
})
```

### Description

Lorem ipsum

Across Kreise (NUTS-3) {data-icon="fa-list"}
=======================================================================

Column {data-width=7, .tabset}
-----------------------------------------------------------------------

### `r emo::ji("clipboard")` Table

`<TODO>`

### `r emo::ji("world_map")` Choropleth map

`<TODO>`

Column {data-width=3}
-----------------------------------------------------------------------

### Description

Lorem ipsum
