---
title: "German Commuter Statistics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: bootstrap
    css: fonts.css
runtime: shiny
---

```{html import-stylesheets, include = FALSE}
<link href='https://fonts.googleapis.com/css?family=Fira+Sans:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap' rel='stylesheet' type='text/css'>
<link href='https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5/distr/fira_code.css' rel='stylesheet' type='text/css'>
```

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(reactable)
library(htmltools)
library(highcharter)

laender_df <- data.table::fread("laender_df.csv", encoding = "UTF-8")
```

Sidebar {.sidebar}
=======================================================================

Access to official data provided by the [datenguide API](https://github.com/datenguide/datenguide-api) -- using the [datenguidepy](https://github.com/CorrelAid/datenguide-python) package

---

```{r}
selectInput("year", label = "Year:",
            choices = 2011:2019, selected = 2019)

selectInput("map_var", label = "Statistic to plot:",
            choices = c("In", "Out", "Balance"), selected = "Balance")

selectInput("get_pct", label = "As a percentage of the population?",
            choices = c("Yes", "No"), selected = "No")
```

```{r prep-df-fn}
transform_stat <- function(data, to_pct = input$get_pct) {
  if (to_pct == "Yes") {
    data %>% 
      mutate(across(c(In, Out, Balance), ~ round(.x * 100 / pop, 2)))
  } else {
    data
  }
}
```

NUTS-1 (Bundesländer)
=======================================================================

Column {data-width=700, .tabset}
-----------------------------------------------------------------------

### Table

```{r laender-tbl}
bar_chart <- function(label, width = "100%", height = "14px", fill = "#cccccc",
                      align = "left") {
  label <- div(style = list(marginLeft = "5px", marginRight = "5px"), label)
  bar <- div(style = list(background = fill, width = width, height = height,
                          float = align))
  if (align == "right") {
    div(style = list(display = "flex", alignItems = "center",
                     justifyContent = "flex-end"), label, bar)
  } else {
    div(style = list(display = "flex", alignItems = "center"), bar, label)
  }
}

renderReactable({
  laender_df %>% 
    transform_stat() %>% 
    filter(year == as.numeric(input$year)) %>% 
    select(Bundesland = name, Out, Balance, In) %>% 
    reactable(
      pagination = FALSE, borderless = TRUE,
      defaultSorted = "Balance", defaultSortOrder = "desc",
      columns = list(
        Bundesland = colDef(defaultSortOrder = "asc"),
        Balance = colDef(
          name = emo::ji("balance_scale"),
          width = 80,
          cell = function(value) format(value, big.mark = " "),
          style = list(background = "#f8f8f8"),
          align = "center"
        ),
        Out = colDef(
          cell = function(value) {
            width <- paste0(value * .7 * 100 / max(.$Out), "%")
            value <- format(value, big.mark = " ")
            bar_chart(value, width = width, fill = "#c7522b", align = "right")
          }
        ),
        In = colDef(
          cell = function(value) {
            width <- paste0(value * .7 * 100 / max(.$Out), "%")
            value <- format(value, big.mark = " ")
            bar_chart(value, width = width, fill = "#008585", align = "left")
          },
          align = "left"
        )
      )
    )
})
```

### Choropleth map

```{r laender-map}
hc_map_colors <- function(hc_map, var) {
  if (var == "Balance") {
      ret <- hc_map %>% 
        hc_colorAxis(stops = JS("[
        [0, '#c7522b'],
        [0.194, '#dea868'], 
        [0.389, '#fbf2c4'],
        [0.583, '#9bbaa0'],
        [0.778, '#008585']
      ]"))
  }
  if (var == "In") {
      ret <- hc_map %>% 
        hc_colorAxis(stops = JS("[
        [0, '#fbf2c4'],
        [0.25, '#c7d6b2'], 
        [0.5, '#9bbaa0'],
        [0.75, '#60a08d'],
        [1, '#008585']
      ]"))
  }
  if (var == "Out") {
      ret <- hc_map %>% 
        hc_colorAxis(stops = JS("[
        [0, '#fbf2c4'],
        [0.25, '#eacd96'], 
        [0.5, '#dea868'],
        [0.75, '#d37f40'],
        [1, '#c7522b']
      ]"))
  }
  ret
}

renderHighchart({
  hcmap(
    "countries/de/de-all.js",
    data = laender_df %>% 
      transform_stat() %>% 
      filter(year == input$year),
    value = input$map_var,
    joinBy = c("woe-name", "name"),
    name = input$map_var,
    dataLabels = list(enabled = TRUE, format = "{point.name}"),
    borderColor = "#fafafa",
    borderWidth = 0.1
  ) %>% 
    hc_map_colors(var = input$map_var) %>% 
    hc_add_theme(hc_theme(chart = list(style = list(
      fontFamily = "var(--text-font-family), var(--text-font-base)",
      fontVariantNumeric = "tabular-nums"
    ))))
})
```

Column {data-width=300}
-----------------------------------------------------------------------

### Description

Lorem ipsum

NUTS-3 (Kreise)
=======================================================================

Column {data-width=700, .tabset}
-----------------------------------------------------------------------

### Table

`<TODO>`

### Choropleth map

`<TODO>`

Column {data-width=300}
-----------------------------------------------------------------------

### Description

Lorem ipsum
